### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by tarrencev** [benchsci/rules_kustomize#11] opened 2022-04-05 20:46 UTC
Hey @bshi 

Hope you are doing well. I'm running into an issue when using this package with arm64 (M1). It looks like we need to add a `kubetctl` `srcs` for `@bazel_tools//src/conditions:darwin_arm64` and `@bazel_tools//src/conditions:linux_aarch64` (for docker images compiled on arm64).

**Comment by bshi** [comment] 2022-04-07 03:56
👋 @tarrencev

Can we use the same Darwin amd64 binary and rely on M1 Rosetta (?) in the short term?  Doesn't look like darwin_arm64 builds are being published officially yet https://gcsweb.k8s.io/gcs/kubernetes-release/release/v0.21.4/

**Comment by bshi** [comment] 2022-04-07 03:58
Accidentally closed.  Re-opening.

**Comment by bshi** [comment] 2022-04-07 04:02
The examples/ dir builds & tests fine on my M1 so I think #12 is sufficient to resolve this for docker Linux environments on M1?

**Comment by crusyn** [comment] 2022-07-13 21:39
Hey guys- getting the following error when trying this on an M1.  It works fine on intel:
```
/root/.cache/bazel/_bazel_root/398f1c4e683b44a3cb982222eee13456/external/com_benchsci_rules_kustomize/BUILD:25:10: no such package '@kubectl_linux_arm64//file': The repository '@kubectl_linux_arm64' could not be resolved and referenced by '@com_benchsci_rules_kustomize//:kubectl_bin
```

I tried poking around to figure out where the files are supposed to be but I'm a bazel amateur so I didn't make too much progress.  Any suggestions on some troubleshooting steps?

**Comment by bshi** [comment] 2022-07-21 04:34
@crusyn can you provide more details or a minimal repro case (e.g. in `examples`)?  I cannot reproduce:

```
benchsci/rules_kustomize/examples$ bazel test //...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed 23 targets (33 packages loaded, 331 targets configured).
INFO: Found 18 targets and 5 test targets...
INFO: Elapsed time: 26.911s, Critical Path: 2.21s
INFO: 36 processes: 22 internal, 14 darwin-sandbox.
INFO: Build completed successfully, 36 total actions
//proj-1/cluster-a/stage:golden                                          PASSED in 0.3s
//proj-1/cluster-a/tools:golden                                          PASSED in 0.6s
//proj-2/cluster-b/prod:parallel_test                                    PASSED in 0.2s
//proj-2/cluster-b/prod:prod.golden                                      PASSED in 0.1s
//proj-3/cluster-c/prod:golden                                           PASSED in 0.7s

Executed 5 out of 5 tests: 5 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to sINFO: Build completed successfully, 36 total actions
```
on
```
benchsci/rules_kustomize/examples$ uname -a
Darwin deathstar2.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```
and
```
bshi@deathstar2 benchsci/rules_kustomize/examples$ bazel version
Bazelisk version: v1.10.1
Build label: 4.2.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 18 12:54:05 2021 (1629291245)
Build timestamp: 1629291245
Build timestamp as int: 1629291245
```

Also tested (by tweaking `examples/.bazelversion`) on bazel versions 4.2.2 & 5.2.0 and could not reproduce.

**Comment by crusyn** [comment] 2022-09-27 21:43
lolz.  The error was pretty plain we were missing:

```
http_file(
  name = "kubectl_linux_arm64",
  executable = True,
  sha256 = "4eadbeabc8b8584d923d54648bd19eb869ac9b7150c8f41cd217c937f49c718b",
  urls = ["https://storage.googleapis.com/kubernetes-release/release/v1.19.11/bin/linux/arm64/kubectl"],
)
```

in our WORKSPACE file.  Was so hard to repro because I tried it outside of my linux container and it worked :)

**Comment by crusyn** [comment] 2022-09-27 21:43
I think we can close this issue.

**Closed as completed** 2022-09-28 21:12 UTC
